CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	message varchar(255) not null,
	source varchar(255) not null
);

create sequence notification_id_sequence start with 1 increment by 1;